[project]
name = "llm-tool-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RakeshNainani", email = "rakeshnainani@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
llm-tool-calling = "llm_tool_calling:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
